// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShakerBusiness.Data;

#nullable disable

namespace ShakerBusiness.Migrations
{
    [DbContext(typeof(ShakerDbContext))]
    [Migration("20260924200829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("ShakerBusiness.Data.AdminBusinessEditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AdminTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("AppliedLive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("OwnedAfter")
                        .HasColumnType("int");

                    b.Property<int>("OwnedBefore")
                        .HasColumnType("int");

                    b.Property<string>("TargetDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TargetTwitchUserId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AdminBusinessEditLogEntries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.AdminEditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AdminTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AngelCountAfter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AngelCountBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("AppliedLive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CashAfter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("CashBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EarningsAtLastResetAfter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EarningsAtLastResetBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LifetimeEarningsAfter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LifetimeEarningsBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double>("OliModifierPercentAfter")
                        .HasColumnType("double");

                    b.Property<double>("OliModifierPercentBefore")
                        .HasColumnType("double");

                    b.Property<int>("PrestigeCountAfter")
                        .HasColumnType("int");

                    b.Property<int>("PrestigeCountBefore")
                        .HasColumnType("int");

                    b.Property<string>("TargetDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TargetTwitchUserId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AdminEditLogEntries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.AdminRoleEditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AdminTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("AppliedLive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ModeratorAfter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ModeratorBefore")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TargetDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TargetTwitchUserId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AdminRoleEditLogEntries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.GlobalGameState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BoostExpiresUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("BoostMultiplier")
                        .HasColumnType("double");

                    b.Property<DateTime?>("GameOverAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("GameOverEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MaintenanceModeEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("GlobalGameStates");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerAccount", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AngelCount")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Cash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EarningsAtLastReset")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("FishingXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsChatBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDev")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastOnlineUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastPrestigeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LifetimeEarnings")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("OliChatRound")
                        .HasColumnType("int");

                    b.Property<double>("OliModifierPercent")
                        .HasColumnType("double");

                    b.Property<int>("PrestigeCount")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ResetCount")
                        .HasColumnType("int");

                    b.Property<int>("SnakeHighScore")
                        .HasColumnType("int");

                    b.Property<int>("TimberHighScore")
                        .HasColumnType("int");

                    b.HasKey("TwitchUserId");

                    b.ToTable("PlayerAccounts");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerAngelUpgrade", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AngelUpgradeId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("TwitchUserId", "AngelUpgradeId");

                    b.ToTable("PlayerAngelUpgrades");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerBaitInventoryEntry", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BaitId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("TwitchUserId", "BaitId");

                    b.ToTable("PlayerBaitInventoryEntries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerBusiness", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BusinessId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("CycleAnchorUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Owned")
                        .HasColumnType("int");

                    b.HasKey("TwitchUserId", "BusinessId");

                    b.ToTable("PlayerBusinesses");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerFishCatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaughtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FishId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId", "FishId");

                    b.ToTable("PlayerFishCatches");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerFishDiscovery", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FishId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("BestLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstCaughtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TwitchUserId", "FishId");

                    b.ToTable("PlayerFishDiscoveries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerFishingProfile", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ActiveBaitId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("Pearls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(100L);

                    b.Property<int>("RodLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("TwitchUserId");

                    b.ToTable("PlayerFishingProfiles");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerFishingQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BatchUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FishId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId");

                    b.ToTable("PlayerFishingQuests");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerUpgrade", b =>
                {
                    b.Property<string>("TwitchUserId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UpgradeId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("TwitchUserId", "UpgradeId");

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("ShakerBusiness.Data.ResetLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AngelCountAfter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AngelCountBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AngelsGained")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("BusinessLevelsBeforeJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CashBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EarningsAtLastResetBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsPrestige")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LifetimeEarningsBefore")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<double>("OliModifierPercentApplied")
                        .HasColumnType("double");

                    b.Property<int>("PrestigeCountAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("TwitchUserId");

                    b.ToTable("ResetLogEntries");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerAngelUpgrade", b =>
                {
                    b.HasOne("ShakerBusiness.Data.PlayerAccount", "Account")
                        .WithMany("AngelUpgrades")
                        .HasForeignKey("TwitchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerBusiness", b =>
                {
                    b.HasOne("ShakerBusiness.Data.PlayerAccount", "Account")
                        .WithMany("Businesses")
                        .HasForeignKey("TwitchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerFishingProfile", b =>
                {
                    b.HasOne("ShakerBusiness.Data.PlayerAccount", "Account")
                        .WithMany()
                        .HasForeignKey("TwitchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerUpgrade", b =>
                {
                    b.HasOne("ShakerBusiness.Data.PlayerAccount", "Account")
                        .WithMany("Upgrades")
                        .HasForeignKey("TwitchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ShakerBusiness.Data.PlayerAccount", b =>
                {
                    b.Navigation("AngelUpgrades");

                    b.Navigation("Businesses");

                    b.Navigation("Upgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
